[package]
name = "yori-regex"
version = "0.1.0"
edition = "2021"

# Designate binary name
[[bin]]
path = "src/main.rs"
name = "regex"

[dependencies]
anyhow = "1.0.77"
clap = { version = "4.4.11", features = ["derive"] }
itertools = "0.12.0"
regex = "1.10.2"
